package com.questlearn.model

import jakarta.persistence.*
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import java.time.Instant

/**
 * Tracks a remediation tutorial assigned to a student after scoring poorly on a quest.
 * The tutorial is auto-generated by Gemini to cover the specific concepts the student missed.
 */
@Entity
@Table(
    name = "student_tutorials",
    indexes = [
        Index(name = "idx_st_student", columnList = "student_id"),
        Index(name = "idx_st_curriculum", columnList = "curriculum_id")
    ]
)
data class StudentTutorial(
    @Id
    @Column(name = "id", nullable = false, length = 100)
    val id: String = "",

    @Column(name = "student_id", nullable = false, length = 50)
    val studentId: String = "",

    @Column(name = "curriculum_id", nullable = false, length = 50)
    val curriculumId: String = "",

    @Column(name = "day_number", nullable = false)
    val dayNumber: Int = 0,

    @Column(name = "quest_id", nullable = false, length = 50)
    val questId: String = "",

    @Column(name = "tutorial_quest_id", nullable = false, length = 50)
    val tutorialQuestId: String = "",

    @Column(name = "score_on_quest", nullable = false)
    val scoreOnQuest: Int = 0,

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "wrong_challenge_ids", columnDefinition = "jsonb", nullable = false)
    val wrongChallengeIds: List<String> = emptyList(),

    @Column(name = "completed", nullable = false)
    val completed: Boolean = false,

    @Column(name = "completed_at")
    val completedAt: Instant? = null,

    @Column(name = "created_at", nullable = false)
    val createdAt: Instant = Instant.now()
)
